// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yrpc_core_protocol/c2s.proto

#include "yrpc_core_protocol/c2s.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR C2S_HEARTBEAT_REQ::C2S_HEARTBEAT_REQ(
    ::_pbi::ConstantInitialized)
  : tick_(0){}
struct C2S_HEARTBEAT_REQDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C2S_HEARTBEAT_REQDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C2S_HEARTBEAT_REQDefaultTypeInternal() {}
  union {
    C2S_HEARTBEAT_REQ _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C2S_HEARTBEAT_REQDefaultTypeInternal _C2S_HEARTBEAT_REQ_default_instance_;
static ::_pb::Metadata file_level_metadata_yrpc_5fcore_5fprotocol_2fc2s_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_yrpc_5fcore_5fprotocol_2fc2s_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_yrpc_5fcore_5fprotocol_2fc2s_2eproto = nullptr;

const uint32_t TableStruct_yrpc_5fcore_5fprotocol_2fc2s_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::C2S_HEARTBEAT_REQ, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::C2S_HEARTBEAT_REQ, tick_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::C2S_HEARTBEAT_REQ)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_C2S_HEARTBEAT_REQ_default_instance_._instance,
};

const char descriptor_table_protodef_yrpc_5fcore_5fprotocol_2fc2s_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\034yrpc_core_protocol/c2s.proto\"!\n\021C2S_HE"
  "ARTBEAT_REQ\022\014\n\004tick\030\001 \001(\005b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_yrpc_5fcore_5fprotocol_2fc2s_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_yrpc_5fcore_5fprotocol_2fc2s_2eproto = {
    false, false, 73, descriptor_table_protodef_yrpc_5fcore_5fprotocol_2fc2s_2eproto,
    "yrpc_core_protocol/c2s.proto",
    &descriptor_table_yrpc_5fcore_5fprotocol_2fc2s_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_yrpc_5fcore_5fprotocol_2fc2s_2eproto::offsets,
    file_level_metadata_yrpc_5fcore_5fprotocol_2fc2s_2eproto, file_level_enum_descriptors_yrpc_5fcore_5fprotocol_2fc2s_2eproto,
    file_level_service_descriptors_yrpc_5fcore_5fprotocol_2fc2s_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_yrpc_5fcore_5fprotocol_2fc2s_2eproto_getter() {
  return &descriptor_table_yrpc_5fcore_5fprotocol_2fc2s_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_yrpc_5fcore_5fprotocol_2fc2s_2eproto(&descriptor_table_yrpc_5fcore_5fprotocol_2fc2s_2eproto);

// ===================================================================

class C2S_HEARTBEAT_REQ::_Internal {
 public:
};

C2S_HEARTBEAT_REQ::C2S_HEARTBEAT_REQ(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:C2S_HEARTBEAT_REQ)
}
C2S_HEARTBEAT_REQ::C2S_HEARTBEAT_REQ(const C2S_HEARTBEAT_REQ& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  tick_ = from.tick_;
  // @@protoc_insertion_point(copy_constructor:C2S_HEARTBEAT_REQ)
}

inline void C2S_HEARTBEAT_REQ::SharedCtor() {
tick_ = 0;
}

C2S_HEARTBEAT_REQ::~C2S_HEARTBEAT_REQ() {
  // @@protoc_insertion_point(destructor:C2S_HEARTBEAT_REQ)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C2S_HEARTBEAT_REQ::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void C2S_HEARTBEAT_REQ::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void C2S_HEARTBEAT_REQ::Clear() {
// @@protoc_insertion_point(message_clear_start:C2S_HEARTBEAT_REQ)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  tick_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C2S_HEARTBEAT_REQ::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 tick = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          tick_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C2S_HEARTBEAT_REQ::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:C2S_HEARTBEAT_REQ)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 tick = 1;
  if (this->_internal_tick() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_tick(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:C2S_HEARTBEAT_REQ)
  return target;
}

size_t C2S_HEARTBEAT_REQ::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:C2S_HEARTBEAT_REQ)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 tick = 1;
  if (this->_internal_tick() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_tick());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C2S_HEARTBEAT_REQ::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    C2S_HEARTBEAT_REQ::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C2S_HEARTBEAT_REQ::GetClassData() const { return &_class_data_; }

void C2S_HEARTBEAT_REQ::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<C2S_HEARTBEAT_REQ *>(to)->MergeFrom(
      static_cast<const C2S_HEARTBEAT_REQ &>(from));
}


void C2S_HEARTBEAT_REQ::MergeFrom(const C2S_HEARTBEAT_REQ& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:C2S_HEARTBEAT_REQ)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_tick() != 0) {
    _internal_set_tick(from._internal_tick());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C2S_HEARTBEAT_REQ::CopyFrom(const C2S_HEARTBEAT_REQ& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:C2S_HEARTBEAT_REQ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2S_HEARTBEAT_REQ::IsInitialized() const {
  return true;
}

void C2S_HEARTBEAT_REQ::InternalSwap(C2S_HEARTBEAT_REQ* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(tick_, other->tick_);
}

::PROTOBUF_NAMESPACE_ID::Metadata C2S_HEARTBEAT_REQ::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_yrpc_5fcore_5fprotocol_2fc2s_2eproto_getter, &descriptor_table_yrpc_5fcore_5fprotocol_2fc2s_2eproto_once,
      file_level_metadata_yrpc_5fcore_5fprotocol_2fc2s_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::C2S_HEARTBEAT_REQ*
Arena::CreateMaybeMessage< ::C2S_HEARTBEAT_REQ >(Arena* arena) {
  return Arena::CreateMessageInternal< ::C2S_HEARTBEAT_REQ >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
