// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yrpc_core_protocol/c2s.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_yrpc_5fcore_5fprotocol_2fc2s_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_yrpc_5fcore_5fprotocol_2fc2s_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_yrpc_5fcore_5fprotocol_2fc2s_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_yrpc_5fcore_5fprotocol_2fc2s_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_yrpc_5fcore_5fprotocol_2fc2s_2eproto;
class C2S_HEARTBEAT_REQ;
struct C2S_HEARTBEAT_REQDefaultTypeInternal;
extern C2S_HEARTBEAT_REQDefaultTypeInternal _C2S_HEARTBEAT_REQ_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::C2S_HEARTBEAT_REQ* Arena::CreateMaybeMessage<::C2S_HEARTBEAT_REQ>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class C2S_HEARTBEAT_REQ final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:C2S_HEARTBEAT_REQ) */ {
 public:
  inline C2S_HEARTBEAT_REQ() : C2S_HEARTBEAT_REQ(nullptr) {}
  ~C2S_HEARTBEAT_REQ() override;
  explicit PROTOBUF_CONSTEXPR C2S_HEARTBEAT_REQ(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C2S_HEARTBEAT_REQ(const C2S_HEARTBEAT_REQ& from);
  C2S_HEARTBEAT_REQ(C2S_HEARTBEAT_REQ&& from) noexcept
    : C2S_HEARTBEAT_REQ() {
    *this = ::std::move(from);
  }

  inline C2S_HEARTBEAT_REQ& operator=(const C2S_HEARTBEAT_REQ& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2S_HEARTBEAT_REQ& operator=(C2S_HEARTBEAT_REQ&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C2S_HEARTBEAT_REQ& default_instance() {
    return *internal_default_instance();
  }
  static inline const C2S_HEARTBEAT_REQ* internal_default_instance() {
    return reinterpret_cast<const C2S_HEARTBEAT_REQ*>(
               &_C2S_HEARTBEAT_REQ_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(C2S_HEARTBEAT_REQ& a, C2S_HEARTBEAT_REQ& b) {
    a.Swap(&b);
  }
  inline void Swap(C2S_HEARTBEAT_REQ* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2S_HEARTBEAT_REQ* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C2S_HEARTBEAT_REQ* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C2S_HEARTBEAT_REQ>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C2S_HEARTBEAT_REQ& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C2S_HEARTBEAT_REQ& from) {
    C2S_HEARTBEAT_REQ::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C2S_HEARTBEAT_REQ* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "C2S_HEARTBEAT_REQ";
  }
  protected:
  explicit C2S_HEARTBEAT_REQ(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTickFieldNumber = 1,
  };
  // int32 tick = 1;
  void clear_tick();
  int32_t tick() const;
  void set_tick(int32_t value);
  private:
  int32_t _internal_tick() const;
  void _internal_set_tick(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:C2S_HEARTBEAT_REQ)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t tick_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_yrpc_5fcore_5fprotocol_2fc2s_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C2S_HEARTBEAT_REQ

// int32 tick = 1;
inline void C2S_HEARTBEAT_REQ::clear_tick() {
  _impl_.tick_ = 0;
}
inline int32_t C2S_HEARTBEAT_REQ::_internal_tick() const {
  return _impl_.tick_;
}
inline int32_t C2S_HEARTBEAT_REQ::tick() const {
  // @@protoc_insertion_point(field_get:C2S_HEARTBEAT_REQ.tick)
  return _internal_tick();
}
inline void C2S_HEARTBEAT_REQ::_internal_set_tick(int32_t value) {
  
  _impl_.tick_ = value;
}
inline void C2S_HEARTBEAT_REQ::set_tick(int32_t value) {
  _internal_set_tick(value);
  // @@protoc_insertion_point(field_set:C2S_HEARTBEAT_REQ.tick)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_yrpc_5fcore_5fprotocol_2fc2s_2eproto
